version: '3'

services:
  mysql-docker-container:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=quelpunto2244
      - MYSQL_DATABASE=hearine
      - MYSQL_PASSWORD=quelpunto2244
      - BUILD_VERSION=1.0-SNAPSHOT
    volumes:
      - /data/mysql
    networks:
      - hearinedep
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=172.22.0.2
      # - DATABASE_HOST=hearinedep_mysql-docker-container_1
      - DATABASE_USER=root
      - DATABASE_NAME=hearine
      - DATABASE_PORT=3306
      - DATABASE_PASSWORD=quelpunto2244
    volumes:
      - /data/spring-boot-app
    networks:
      - hearinedep
networks:
  hearinedep:
    driver: bridge
